version: "3"
services:
  app:
    build: ./app
    depends_on:
      - db
    ports:
      - 8001:5000


  db:
    platform: linux/x86_64
    
    image: mysql:latest
  
    ports:
      - "30000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: students
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro